services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: food_delivery
      DB_USER: user
      DB_PASSWORD: password
    volumes:
      - ./HTML:/usr/local/tomcat/webapps/ROOT/HTML
      - ./JS:/usr/local/tomcat/webapps/ROOT/JS
      - ./CSS:/usr/local/tomcat/webapps/ROOT/CSS
      - ./IMAGES:/usr/local/tomcat/webapps/ROOT/IMAGES
      - ./WEB-INF:/usr/local/tomcat/webapps/ROOT/WEB-INF

  db:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: food_delivery
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./SQL/init.sql:/docker-entrypoint-initdb.d/init.sql